{
    "data_list": [
        {
            "title": "One Piece: Vol. 61, Romance Dawn of the New World",
            "authors": ["Eiichiro Oda"],
            "genres": ["Action", "Adventure", "Fantasy", "Manga"],
            "published_year": 2011,
            "publisher": "Shueisha",
            "pages": 200,
        },
        {
            "title": "Naruto: Vol. 27, Awakening",
            "authors": ["Masashi Kishimoto"],
            "genres": ["Action", "Adventure", "Fantasy", "Manga"],
            "published_year": 2005,
            "publisher": "Shueisha",
            "pages": 192,
        },
        {
            "title": "Attack on Titan: Vol. 16, His Father's Sin",
            "authors": ["Hajime Isayama"],
            "genres": ["Action", "Fantasy", "Post-Apocalyptic", "Manga"],
            "published_year": 2014,
            "publisher": "Kodansha",
            "pages": 192,
        },
        {
            "title": "Death Note: Vol. 6, Give-and-Take",
            "authors": ["Tsugumi Ohba"],
            "genres": ["Thriller", "Mystery", "Supernatural", "Manga"],
            "published_year": 2004,
            "publisher": "Shueisha",
            "pages": 200,
        },
        {
            "title": "Jujutsu Kaisen: Vol. 17, Shibuya Incident",
            "authors": ["Gege Akutami"],
            "genres": ["Action", "Supernatural", "Horror", "Manga"],
            "published_year": 2022,
            "publisher": "Shueisha",
            "pages": 208,
        },
        {
            "title": "Laskar Pelangi",
            "authors": ["Andrea Hirata"],
            "genres": ["Historical", "Coming-of-age", "Novel"],
            "published_year": 2005,
            "publisher": "Bentang Pustaka",
            "pages": 380,
        },
        {
            "title": "Assalamualaikum Beijing",
            "authors": ["Asma Nadia"],
            "genres": ["Drama", "Romance", "Novel"],
            "published_year": 2011,
            "publisher": "Republika Penerbit",
            "pages": 448,
        },
        {
            "title": "Laut Tengah",
            "authors": ["Leila S. Chudori"],
            "genres": ["Drama", "Historical Fiction", "Novel"],
            "published_year": 2017,
            "publisher": "Gramedia Pustaka Utama",
            "pages": 352,
        },
        {
            "title": "Dear Nathan Hello Salma",
            "authors": ["Erisca Febriani"],
            "genres": ["Drama", "Romance", "Novel"],
            "published_year": 2017,
            "publisher": "Matahati",
            "pages": 320,
        },
        {
            "title": "Rindu",
            "authors": ["Tere Liye"],
            "genres": ["Drama", "Romance", "Novel"],
            "published_year": 2014,
            "publisher": "Gramedia Pustaka Utama",
            "pages": 448,
        },
        {
            "title": "Perahu Kertas",
            "authors": ["Dee Lestari"],
            "genres": ["Drama", "Romance", "Novel"],
            "published_year": 2009,
            "publisher": "Bentang Pustaka",
            "pages": 500,
        },
        {
            "title": "Jangan Jadi Muslimah Nyebelin",
            "authors": ["Asma Nadia"],
            "genres": ["Religious", "Self-Improvement", "Novel"],
            "published_year": 2012,
            "publisher": "Soka Publishing",
            "pages": 186,
        },
        {
            "title": "Sang Pemimpi",
            "authors": ["Andrea Hirata"],
            "genres": ["Biography", "Coming-of-age", "Novel"],
            "published_year": 2006,
            "publisher": "Bentang Pustaka",
            "pages": 529,
        },
        {
            "title": "Bumi",
            "authors": ["Tere Liye"],
            "genres": ["Drama", "Romance", "Novel"],
            "published_year": 2016,
            "publisher": "Gramedia Pustaka Utama",
            "pages": 464,
        },
        {
            "title": "Selamanya Cinta",
            "authors": ["Asma Nadia"],
            "genres": ["Romance", "Family", "Novel"],
            "published_year": 2013,
            "publisher": "Soka Publishing",
            "pages": 310,
        },
        {
            "title": "Maryamah Karpov",
            "authors": ["Andrea Hirata"],
            "genres": ["Drama", "Coming-of-age", "Novel"],
            "published_year": 2008,
            "publisher": "Bentang Pustaka",
            "pages": 452,
        },
        {
            "title": "Eloquent JavaScript",
            "authors": ["Marijn Haverbeke"],
            "genres": ["Web Development", "JavaScript"],
            "published_year": 2011,
            "publisher": "No Starch Press",
            "pages": 472,
        },
        {
            "title": "Learning Web Design",
            "authors": ["Jennifer Niederst Robbins"],
            "genres": ["Web Development", "HTML", "CSS"],
            "published_year": 2018,
            "publisher": "O'Reilly Media",
            "pages": 808,
        },
        {
            "title": "CSS Secrets",
            "authors": ["Lea Verou"],
            "genres": ["Web Development", "CSS"],
            "published_year": 2015,
            "publisher": "O'Reilly Media",
            "pages": 392,
        },
        {
            "title": "JavaScript: The Good Parts",
            "authors": ["Douglas Crockford"],
            "genres": ["Web Development", "JavaScript"],
            "published_year": 2008,
            "publisher": "O'Reilly Media",
            "pages": 176,
        },
        {
            "title": "The Pragmatic Programmer",
            "authors": ["Andrew Hunt", "David Thomas"],
            "genres": ["Web Development", "Software Engineering"],
            "published_year": 1999,
            "publisher": "Addison-Wesley Professional",
            "pages": 352,
        },
        {
            "title": "The 7 Habits of Highly Effective People",
            "authors": ["Stephen R. Covey"],
            "genres": ["Motivational", "Self-Improvement"],
            "published_year": 1989,
            "publisher": "Free Press",
            "pages": 381,
        },
        {
            "title": "Think and Grow Rich",
            "authors": ["Napoleon Hill"],
            "genres": ["Motivational", "Personal Finance"],
            "published_year": 1937,
            "publisher": "The Ralston Society",
            "pages": 238,
        },
        {
            "title": "The Power of Now",
            "authors": ["Eckhart Tolle"],
            "genres": ["Spirituality", "Self-Improvement", "Motivational"],
            "published_year": 1997,
            "publisher": "New World Library",
            "pages": 236,
        },
        {
            "title": "Atomic Habits",
            "authors": ["James Clear"],
            "genres": ["Motivational", "Self-Improvement"],
            "published_year": 2018,
            "publisher": "Avery",
            "pages": 320,
        },
        {
            "title": "Man's Search for Meaning",
            "authors": ["Viktor E. Frankl"],
            "genres": ["Psychology", "Existentialism", "Motivational"],
            "published_year": 1946,
            "publisher": "Beacon Press",
            "pages": 165,
        },
        {
            "title": "Panduan Sehat Ala Rasulullah",
            "authors": ["Dr. Abdul Mun'im IDI"],
            "genres": ["Men's Health", "Islamic Health", "Spirituality"],
            "published_year": 2015,
            "publisher": "Pustaka Amani",
            "pages": 240,
        },
        {
            "title": "Kuasai Kekuatanmu: Rileks, Tampil Segar, dan Sehat Optimal",
            "authors": ["Dr. Dradjat R. Suardi"],
            "genres": ["Men's Health", "Self-Improvement"],
            "published_year": 2017,
            "publisher": "Gramedia Pustaka Utama",
            "pages": 248,
        },
        {
            "title": "Kesehatan Pria: Buku Kesehatan Laki-laki Terlengkap",
            "authors": ["Dr. Wimpie Pangkahila"],
            "genres": ["Men's Health", "Comprehensive Health Guide"],
            "published_year": 2018,
            "publisher": "Pustaka Al Hidayah",
            "pages": 300,
        },
        {
            "title": "Pria yang Sehat, Bahagia, dan Sukses",
            "authors": ["Dr. M. Jusuf Sjarif Damai"],
            "genres": ["Men's Health", "Success"],
            "published_year": 2016,
            "publisher": "Andi Publisher",
            "pages": 224,
        },
        {
            "title": "Men's Health: The Complete Guide to a Better Body and a Better Sex Life",
            "authors": ["Dr. Tommy H. Lianto"],
            "genres": ["Men's Health", "Fitness", "Sexuality"],
            "published_year": 2015,
            "publisher": "Penerbit Literasi Media",
            "pages": 280,
        },
        {
            "title": "Mechanical Engineering Design, 9th Edition",
            "authors": [
                "Joseph Edward Shigley",
                "Charles R. Mischke",
                "Richard G. Budynas",
            ],
            "genres": ["Mechanical Engineering"],
            "published_year": 2010,
            "publisher": "McGraw-Hill",
            "pages": 1120,
        },
        {
            "title": "Mechanics of Materials",
            "authors": [
                "Ferdinand P. Beer",
                "E. Russell Johnston Jr.",
                "John T. DeWolf",
                "David F. Mazurek",
            ],
            "genres": ["Mechanical Engineering", "Materials Science"],
            "published_year": 2014,
            "publisher": "McGraw-Hill",
            "pages": 896,
        },
        {
            "title": "Engineering Mechanics: Dynamics",
            "authors": ["R. C. Hibbeler", "Kai Beng Yap"],
            "genres": ["Mechanical Engineering", "Engineering Mechanics"],
            "published_year": 2012,
            "publisher": "Pearson",
            "pages": 800,
        },
        {
            "title": "Introduction to Autonomous Robots: From Kinematics to Control",
            "authors": ["Roland Siegwart", "Illah Nourbakhsh", "Davide Scaramuzza"],
            "genres": ["Robotics", "Autonomous Systems"],
            "published_year": 2011,
            "publisher": "The MIT Press",
            "pages": 472,
        },
        {
            "title": "Robot Modeling and Control",
            "authors": ["Mark W. Spong", "Seth Hutchinson", "M. Vidyasagar"],
            "genres": ["Robotics", "Control Systems"],
            "published_year": 2005,
            "publisher": "Wiley",
            "pages": 592,
        },
        {
            "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
            "authors": ["Robert C. Martin", "Micah Martin"],
            "genres": ["Software Development", "Programming"],
            "published_year": 2008,
            "publisher": "Prentice Hall",
            "pages": 464,
        },
        {
            "title": "Design Patterns: Elements of Reusable Object-Oriented Software",
            "authors": [
                "Erich Gamma",
                "Richard Helm",
                "Ralph Johnson",
                "John Vlissides",
            ],
            "genres": ["Software Development", "Design Patterns"],
            "published_year": 1994,
            "publisher": "Addison-Wesley Professional",
            "pages": 395,
        },
        {
            "title": "Extreme Programming Explained: Embrace Change",
            "authors": ["Kent Beck", "Cynthia Andres"],
            "genres": ["Software Development", "Agile Methodologies"],
            "published_year": 2004,
            "publisher": "Addison-Wesley Professional",
            "pages": 224,
        },
        {
            "title": "Flask Web Development: Developing Web Applications with Python",
            "authors": ["Miguel Grinberg"],
            "genres": ["Web Development", "Python", "Flask"],
            "published_year": 2018,
            "publisher": "O'Reilly Media",
            "pages": 618,
        },
        {
            "title": "RESTful Web APIs",
            "authors": ["Leonard Richardson", "Mike Amundsen", "Sam Ruby"],
            "genres": ["Web Development", "API Design"],
            "published_year": 2013,
            "publisher": "O'Reilly Media",
            "pages": 408,
        },
        {
            "title": "RESTful API Design: Best Practices in API Design with REST",
            "authors": ["Masse, D.", "Tropashko, V."],
            "genres": ["Web Development", "API Design"],
            "published_year": 2018,
            "publisher": "O'Reilly Media",
            "pages": 300,
        },
        {
            "title": "PostgreSQL: Up and Running",
            "authors": ["Regina O. Obe", "Leo S. Hsu"],
            "genres": ["Database Management", "PostgreSQL"],
            "published_year": 2017,
            "publisher": "O'Reilly Media",
            "pages": 326,
        },
        {
            "title": "Flask Web Development with Python Tutorial",
            "authors": ["William Vincent"],
            "genres": ["Web Development", "Python", "Flask"],
            "published_year": 2020,
            "publisher": "Independently published",
            "pages": 604,
        },
        {
            "title": "Explore Flask: Building Python Web Services",
            "authors": ["Robert Picard"],
            "genres": ["Web Development", "Python", "Flask"],
            "published_year": 2019,
            "publisher": "Apress",
            "pages": 261,
        },
        {
            "title": "A Study in Scarlet",
            "authors": ["Arthur Conan Doyle"],
            "genres": ["Mystery", "Detective"],
            "published_year": 1887,
            "publisher": "Ward, Lock & Co.",
            "pages": 193,
        },
        {
            "title": "The Adventures of Sherlock Holmes",
            "authors": ["Arthur Conan Doyle"],
            "genres": ["Mystery", "Detective"],
            "published_year": 1892,
            "publisher": "George Newnes Ltd.",
            "pages": 307,
        },
        {
            "title": "The Hound of the Baskervilles",
            "authors": ["Arthur Conan Doyle"],
            "genres": ["Mystery", "Detective"],
            "published_year": 1902,
            "publisher": "George Newnes Ltd.",
            "pages": 256,
        },
        {
            "title": "The Sign of the Four",
            "authors": ["Arthur Conan Doyle"],
            "genres": ["Mystery", "Detective"],
            "published_year": 1890,
            "publisher": "Spencer Blackett",
            "pages": 129,
        },
        {
            "title": "The Memoirs of Sherlock Holmes",
            "authors": ["Arthur Conan Doyle"],
            "genres": ["Mystery", "Detective"],
            "published_year": 1893,
            "publisher": "George Newnes Ltd.",
            "pages": 279,
        },
        {
            "title": "Harry Potter and the Philosopher's Stone",
            "authors": ["J.K. Rowling"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 1997,
            "publisher": "Bloomsbury Publishing",
            "pages": 223,
        },
        {
            "title": "Harry Potter and the Prisoner of Azkaban",
            "authors": ["J.K. Rowling"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 1999,
            "publisher": "Bloomsbury Publishing",
            "pages": 317,
        },
        {
            "title": "Harry Potter and the Goblet of Fire",
            "authors": ["J.K. Rowling"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 2000,
            "publisher": "Bloomsbury Publishing",
            "pages": 636,
        },
        {
            "title": "Harry Potter and the Half-Blood Prince",
            "authors": ["J.K. Rowling"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 2005,
            "publisher": "Bloomsbury Publishing",
            "pages": 607,
        },
        {
            "title": "Harry Potter and the Deathly Hallows",
            "authors": ["J.K. Rowling"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 2007,
            "publisher": "Bloomsbury Publishing",
            "pages": 607,
        },
        {
            "title": "Harry Potter and the Chamber of Secrets",
            "authors": ["J.K. Rowling"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 1998,
            "publisher": "Bloomsbury Publishing",
            "pages": 251,
        },
        {
            "title": "Harry Potter and the Order of the Phoenix",
            "authors": ["J.K. Rowling"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 2003,
            "publisher": "Bloomsbury Publishing",
            "pages": 766,
        },
        {
            "title": "It",
            "authors": ["Stephen King"],
            "genres": ["Horror", "Thriller"],
            "published_year": 1986,
            "publisher": "Viking Press",
            "pages": 1138,
        },
        {
            "title": "The Exorcist",
            "authors": ["William Peter Blatty"],
            "genres": ["Horror", "Thriller"],
            "published_year": 1971,
            "publisher": "Harper & Row",
            "pages": 340,
        },
        {
            "title": "The Lord of the Rings",
            "authors": ["J.R.R. Tolkien"],
            "genres": ["Fantasy", "Adventure"],
            "published_year": 1954,
            "publisher": "Allen & Unwin",
            "pages": 1178,
        },
        {
            "title": "The Maze Runner",
            "authors": ["James Dashner"],
            "genres": ["Young Adult", "Dystopian", "Science Fiction"],
            "published_year": 2009,
            "publisher": "Delacorte Press",
            "pages": 375,
        },
        {
            "title": "The Scorch Trials",
            "authors": ["James Dashner"],
            "genres": ["Young Adult", "Dystopian", "Science Fiction"],
            "published_year": 2010,
            "publisher": "Delacorte Press",
            "pages": 361,
        },
        {
            "title": "The Death Cure",
            "authors": ["James Dashner"],
            "genres": ["Young Adult", "Dystopian", "Science Fiction"],
            "published_year": 2011,
            "publisher": "Delacorte Press",
            "pages": 325,
        },
        {
            "title": "Divergent",
            "authors": ["Veronica Roth"],
            "genres": ["Young Adult", "Dystopian", "Science Fiction"],
            "published_year": 2011,
            "publisher": "Katherine Tegen Books",
            "pages": 487,
        },
        {
            "title": "Insurgent",
            "authors": ["Veronica Roth"],
            "genres": ["Young Adult", "Dystopian", "Science Fiction"],
            "published_year": 2012,
            "publisher": "Katherine Tegen Books",
            "pages": 525,
        },
        {
            "title": "Allegiant",
            "authors": ["Veronica Roth"],
            "genres": ["Young Adult", "Dystopian", "Science Fiction"],
            "published_year": 2013,
            "publisher": "Katherine Tegen Books",
            "pages": 526,
        },
        {
            "title": "The Hunger Games",
            "authors": ["Suzanne Collins"],
            "genres": ["Young Adult", "Dystopian", "Science Fiction"],
            "published_year": 2008,
            "publisher": "Scholastic Corporation",
            "pages": 374,
        },
        {
            "title": "Twilight",
            "authors": ["Stephenie Meyer"],
            "genres": ["Young Adult", "Fantasy", "Romance"],
            "published_year": 2005,
            "publisher": "Little, Brown and Company",
            "pages": 498,
        },
        {
            "title": "The Fault in Our Stars",
            "authors": ["John Green"],
            "genres": ["Young Adult", "Contemporary", "Romance"],
            "published_year": 2012,
            "publisher": "Dutton Books",
            "pages": 313,
        },
        {
            "title": "The Da Vinci Code",
            "authors": ["Dan Brown"],
            "genres": ["Mystery", "Thriller"],
            "published_year": 2003,
            "publisher": "Doubleday",
            "pages": 454,
        },
        {
            "title": "The Encyclopedia of World History",
            "authors": ["Peter N. Stearns", "William L. Langer"],
            "genres": ["Encyclopedia", "History"],
            "published_year": 2001,
            "publisher": "Houghton Mifflin Harcourt",
            "pages": 1344,
        },
        {
            "title": "The Encyclopedia of Human Anatomy",
            "authors": ["Kent M. Van De Graaff", "R. Ward Rhees"],
            "genres": ["Encyclopedia", "Anatomy"],
            "published_year": 2014,
            "publisher": "Morton Publishing Company",
            "pages": 688,
        },
        {
            "title": "Encyclopedia of Mathematics",
            "authors": ["James Stuart Tanton"],
            "genres": ["Encyclopedia", "Mathematics"],
            "published_year": 2012,
            "publisher": "Facts On File",
            "pages": 840,
        },
        {
            "title": "The Encyclopedia of Animals",
            "authors": ["Philip Whitfield"],
            "genres": ["Encyclopedia", "Zoology"],
            "published_year": 2006,
            "publisher": "Thunder Bay Press",
            "pages": 256,
        },
        {
            "title": "The Cambridge Encyclopedia of Astronomy",
            "authors": ["Michael E. Bakich"],
            "genres": ["Encyclopedia", "Astronomy"],
            "published_year": 2017,
            "publisher": "Cambridge University Press",
            "pages": 400,
        },
    ]
}
