"""pages and year as small integer type

Revision ID: 28de96050dda
Revises: 4a75b58511ed
Create Date: 2023-06-14 13:46:48.771483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28de96050dda'
down_revision = '4a75b58511ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_year', sa.SmallInteger(), nullable=True))
        batch_op.alter_column('pages',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('published_year')

    # ### end Alembic commands ###
