"""add is_show column to each entitiy

Revision ID: 2e2d1164ab06
Revises: 99fb9106e4ab
Create Date: 2023-06-16 10:42:31.393307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2d1164ab06'
down_revision = '99fb9106e4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.Boolean(), nullable=True))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.Boolean(), nullable=True))

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('borrow_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_show', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_show')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_column('is_show')

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('borrow_book_id_fkey', 'book', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('is_show')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('is_show')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('is_show')

    # ### end Alembic commands ###
