"""default pages value: 1

Revision ID: 4a75b58511ed
Revises: 1e9f6d982992
Create Date: 2023-06-14 13:12:41.428307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a75b58511ed'
down_revision = '1e9f6d982992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('pages',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
