"""add borrow_list in User table

Revision ID: 99fb9106e4ab
Revises: 74bde6da23fe
Create Date: 2023-06-15 16:22:05.961401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fb9106e4ab'
down_revision = '74bde6da23fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint('borrow_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('borrow_book_id_fkey', 'book', ['book_id'], ['id'])

    # ### end Alembic commands ###
