"""add birth year column in author

Revision ID: ae9e091bfd76
Revises: 7fa157575e9c
Create Date: 2023-06-14 15:53:44.160061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9e091bfd76'
down_revision = '7fa157575e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
